version: '3.3'
services:
    wechatpchook:
        container_name: comwechat
        environment:
          - VNCPASS=<YOURR_PASSWORD>
          - COMWECHAT=https://github.com/ljc545w/ComWeChatRobot/releases/download/3.7.0.30-0.1.0-pre/3.7.0.30-0.1.0-pre.zip
        ipc: host
        volumes:
          - "/data/ComWeChatRobot/WeChat Files/:/home/user/.wine/drive_c/users/user/My Documents/WeChat Files/"
          - "/data/ComWeChatRobot/Application Data/:/home/user/.wine/drive_c/users/user/Application Data/"
          - "/etc/localtime:/etc/localtime"
        privileged: true
        restart: always
        network_mode: host
        image: tomsnow1999/docker-com_wechat_robot:latest
    comwechat-slave:
        container_name: comwechat-slave
        ipc: host
        volumes:
          - "/data/ehforwarderbot/blueset.telegram:/root/.ehforwarderbot/profiles/default/blueset.telegram"
          - "/data/ehforwarderbot/honus.comwechat:/root/.ehforwarderbot/profiles/default/honus.comwechat"
          - "/data/ehforwarderbot/QQ_War.keyword_reply:/root/.ehforwarderbot/profiles/default/QQ_War.keyword_reply"
          - "/data/ehforwarderbot/QQ_War.message_merge:/root/.ehforwarderbot/profiles/default/QQ_War.message_merge"
          - "/data/ComWeChatRobot/WeChat\ Files:/root/wechat/files"
        privileged: true
        restart: always
        network_mode: host
        image: honus/efb-wechat-comwechat-slave:latest